# Generated by Django 6.0.2 on 2026-03-11 09:39

import api.policies.models
import api.policies.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0005_alter_policy_policy_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(default=api.policies.utils.generate_application_id, editable=False, max_length=20, unique=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('payment_frequency', models.CharField(blank=True, max_length=10, null=True)),
                ('document', models.FileField(blank=True, help_text='Upload proof document (ID, medical record, vehicle papers, etc.)', null=True, upload_to=api.policies.models.policy_application_upload_path)),
                ('policy_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.policytier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'policy_tier')},
            },
        ),
        migrations.CreateModel(
            name='CarPolicyApplication',
            fields=[
                ('policyapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policies.policyapplication')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_year', models.PositiveIntegerField()),
                ('driver_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Car Policy Application',
                'verbose_name_plural': 'Car Policy Applications',
            },
            bases=('policies.policyapplication',),
        ),
        migrations.CreateModel(
            name='HealthPolicyApplication',
            fields=[
                ('policyapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policies.policyapplication')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('beneficiaries', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Health Policy Application',
                'verbose_name_plural': 'Health Policy Applications',
            },
            bases=('policies.policyapplication',),
        ),
        migrations.CreateModel(
            name='HomePolicyApplication',
            fields=[
                ('policyapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policies.policyapplication')),
                ('property_address', models.TextField()),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Home Policy Application',
                'verbose_name_plural': 'Home Policy Applications',
            },
            bases=('policies.policyapplication',),
        ),
        migrations.CreateModel(
            name='LifePolicyApplication',
            fields=[
                ('policyapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='policies.policyapplication')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=50)),
                ('dependents', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Life Policy Application',
                'verbose_name_plural': 'Life Policy Applications',
            },
            bases=('policies.policyapplication',),
        ),
    ]
