# Generated by Django 6.0.2 on 2026-03-13 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_policytier_tier_name'),
        ('policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='policyapplication',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='policyapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'policy_tier'), name='unique_pending_application'),
        ),
    ]
