# Generated by Django 6.0.2 on 2026-03-17 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_policytier_tier_name'),
        ('policies', '0002_alter_policyapplication_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_title', models.CharField(max_length=100)),
                ('policy_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='admin_panel.policytier')),
            ],
        ),
    ]
