# Generated by Django 6.0.2 on 2026-02-13 13:19

import api.policies.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(default=api.policies.utils.generate_policy_id, max_length=20, unique=True)),
                ('policy_type', models.CharField(choices=[('car', 'Car Insurance'), ('health', 'Health Insurance'), ('home', 'Home Insurance'), ('life', 'Life Insurance')], max_length=20)),
                ('policy_name', models.CharField(max_length=100)),
                ('policy_description', models.TextField()),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('policy_start_date', models.DateField()),
                ('policy_end_date', models.DateField()),
                ('policy_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('policy_created_at', models.DateTimeField(auto_now_add=True)),
                ('policy_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
