# Generated by Django 6.0.2 on 2026-02-13 13:53

import api.policies.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='policy_end_date',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='policy_start_date',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='policy_status',
        ),
        migrations.AddField(
            model_name='policy',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='coverage_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_id',
            field=models.CharField(default=api.policies.utils.generate_policy_id, editable=False, max_length=20, unique=True),
        ),
    ]
