# Generated by Django 6.0.2 on 2026-02-14 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_remove_policy_policy_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='coverage_amount',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='premium_amount',
        ),
        migrations.CreateModel(
            name='PolicyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(choices=[('normal', 'Normal'), ('premium', 'Premium')], max_length=20)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('weekly', 'Weekly')], default='yearly', help_text='Payment frequency for this tier', max_length=10)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='admin_panel.policy')),
            ],
        ),
        migrations.CreateModel(
            name='UserPolicySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('weekly', 'Weekly')], help_text='Allows user to override default frequency if needed', max_length=10, null=True)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('policy_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.policytier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
