# Generated by Django 6.0.2 on 2026-02-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_policy_coverage_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policytier',
            name='premium_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('weekly', 'Weekly')], default='monthly', help_text='Payment frequency for this tier', max_length=10),
        ),
    ]
