# Generated by Django 6.0.2 on 2026-03-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_policytier_premium_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(blank=True, choices=[('vehicle', 'Vehicle Insurance'), ('health', 'Health Insurance'), ('home', 'Home Insurance'), ('life', 'Life Insurance')], max_length=20, null=True),
        ),
    ]
