# Generated by Django 6.0.2 on 2026-03-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_policy_policy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policytier',
            name='tier_name',
            field=models.CharField(choices=[('normal', 'Normal'), ('Basic Coverage', 'Basic Coverage'), ('premium', 'Premium')], max_length=20),
        ),
    ]
