# Generated by Django 6.0.2 on 2026-03-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_policytier_tier_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policytier',
            old_name='premium_amount',
            new_name='monthly_amount',
        ),
        migrations.AddField(
            model_name='policytier',
            name='weekly_amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policytier',
            name='premium_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly')], default='monthly', help_text='Payment frequency for this tier', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpolicyselection',
            name='selected_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('weekly', 'Weekly')], help_text='Allows user to override default frequency if needed', max_length=10, null=True),
        ),
    ]
