# Generated by Django 6.0.2 on 2026-03-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_rename_premium_amount_policytier_monthly_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policytier',
            name='premium_frequency',
        ),
        migrations.AddField(
            model_name='policytier',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policytier',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policytier',
            name='tier_name',
            field=models.CharField(choices=[('normal', 'Normal'), ('Basic', 'Basic Coverage'), ('premium', 'Premium')], max_length=20),
        ),
    ]
