# Generated by Django 6.0.2 on 2026-03-28 08:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_remove_policytier_premium_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='policy_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
