# Generated by Django 6.0.2 on 2026-03-28 08:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_alter_policy_policy_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
