# Generated by Django 6.0.2 on 2026-02-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('agent', 'Agent')], default='user', max_length=20),
        ),
    ]
